# Generated by Django 4.2.4 on 2023-08-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ristorante',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='ristoranti/'),
        ),
    ]
