# Generated by Django 4.2.4 on 2023-08-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0002_ristorante_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ristorante',
            name='menu',
            field=models.TextField(null=True),
        ),
    ]
