# Generated by Django 4.2.4 on 2023-08-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0004_piatto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Piatto',
        ),
    ]
