# Generated by Django 4.2.4 on 2023-08-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0006_piatto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ristorante',
            name='menu',
        ),
        migrations.AddField(
            model_name='piatto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
