# Generated by Django 4.1.7 on 2023-08-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0008_recensione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensione',
            name='valutazione',
        ),
    ]
