# Generated by Django 4.1.7 on 2023-08-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0009_remove_recensione_valutazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='valutazione',
            field=models.CharField(default='3 stelle', max_length=10),
        ),
    ]
